services:
    db:
        image: postgres:17.5
        restart: always
        container_name: database
        volumes:
            - pg-data:/var/lib/postgresql/data
        environment: # Used by the postgres image to setup a default user. For security reason, you should avoid using the postgres user
            POSTGRES_USER: enkiro_dev_user
            POSTGRES_PASSWORD: enkiro_dev_pass # ggshield:ignore
            POSTGRES_DB: enkiro_dev
    
    app:
        container_name: enkiro-app
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        command: iex -S mix phx.server
        tty: true
        stdin_open: true
        volumes:
            - .:/app
        env_file:
            - .env
        depends_on:
            - db
        ports:
            - 4000:4000

volumes:
    pg-data:
        external: true # Must use "docker volume create --name=pg-data before