import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :enkiro, EnkiroWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Enkiro.Finch

# Do not include development routes in production builds.
config :enkiro, :dev_routes, false

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

config :enkiro, Enkiro.Guardian,
  issuer: "enkiro",
  # The secret_key will be loaded from the environment in runtime.exs
  secret_key: nil,
  ttl: {15, :minute},
  module: Enkiro.Guardian,
  error_handler: Enkiro.AuthErrorHandler,
  hooks: Guardian.DB,
  db_module: Enkiro.Guardian.Token,
  repo: Enkiro.Repo

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
